#!/usr/local/bin/node
var links = {
	local: {
	uk: 'http://asicsuk.local:9001',
	au: 'http://asicsau.local:9001',
	de: 'http://asicsde.local:9001',
	es: 'http://asicses.local:9001',
	fr: 'http://asicsfr.local:9001',
	us: 'http://asics.local:9001',
	jp: 'http://asicsjp.local:9001'
	},
	test: {
	uk: 'http://asicsuk-test2.amaze.com:9001/asicsstorefront',
	au: 'http://asicsau-test2.amaze.com:9001/asicsstorefront',
	de: 'http://asicsde-test2.amaze.com:9001/asicsstorefront/de/de-de',
	us: 'http://asics-test2.amaze.com:9001/asicsstorefront',
	jp: 'http://asicsjp-test2.amaze.com:9001/asicsstorefront'
	},
	staging: {
	uk: 'http://asicsuk-staging2.amaze.com:9001/asicsstorefront',
	au: 'http://asicsau-staging2.amaze.com:9001/asicsstorefront',
	de: 'http://asicsde-staging2.amaze.com:9001/de-de/search/',
	us: 'http://asics-staging2.amaze.com:9001',
	jp: 'http://asicsjp-staging2.amaze.com:9001/asicsstorefront'
	},
	ecstage: {
	uk: 'http://www.hybris.ecstage-uk.asics.com',
	de: 'http://www.hybris.ecstage.asics.com/de/de-de',
	us: 'http://www.hybris.ecstage-ac.asics.com'
	},
	live: {
		uk: 'http://www.asics.co.uk',
		au: 'http://www.asics.com.au',
		fr: 'http://www-origin.asics.com/fr/fr-fr'
	}
}

var sys = require('sys')
var exec = require('child_process').exec;
console.log(process.argv);
var myArgs = process.argv.slice(2);
console.log(myArgs);
console.log(links);
function puts(error, stdout, stderr) { sys.puts(stdout) }
exec("open -a 'Google Chrome' " + links[myArgs[0]][myArgs[1]], puts);
